// <auto-generated />
using System;
using Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(ThuVienDbContext))]
    [Migration("20211101075905_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Database.Model.DocGia", b =>
                {
                    b.Property<int>("sMaDocGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dNgayLapThe")
                        .HasColumnType("datetime2");

                    b.Property<string>("sDiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sGioiTinh")
                        .HasColumnType("int");

                    b.Property<DateTime>("sNgayHetHan")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("sNgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("sPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sQueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTenDocGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sMaDocGia");

                    b.ToTable("DocGias");
                });

            modelBuilder.Entity("Database.Model.Sach", b =>
                {
                    b.Property<int>("sMaSach")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dNgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<int>("iNamXuatBan")
                        .HasColumnType("int");

                    b.Property<string>("sNhaXuatBan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTacGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTenSach")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sTheLoai")
                        .HasColumnType("int");

                    b.Property<int>("sTinhTrang")
                        .HasColumnType("int");

                    b.HasKey("sMaSach");

                    b.ToTable("Sachs");
                });

            modelBuilder.Entity("Database.Model.TheMuon", b =>
                {
                    b.Property<int>("sMaThe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dNgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dNgayTra")
                        .HasColumnType("datetime2");

                    b.Property<double>("fGiaThue")
                        .HasColumnType("float");

                    b.Property<int>("sMaDocGia")
                        .HasColumnType("int");

                    b.Property<int>("sMaNhanVien")
                        .HasColumnType("int");

                    b.Property<int>("sMaSach")
                        .HasColumnType("int");

                    b.HasKey("sMaThe");

                    b.HasIndex("sMaDocGia");

                    b.HasIndex("sMaNhanVien");

                    b.HasIndex("sMaSach");

                    b.ToTable("TheMuons");
                });

            modelBuilder.Entity("Database.Model.ThuThu", b =>
                {
                    b.Property<int>("sMaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("cChucVu")
                        .HasColumnType("int");

                    b.Property<DateTime>("dNgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<int>("iTuoi")
                        .HasColumnType("int");

                    b.Property<string>("sDiaChi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sGioiTinh")
                        .HasColumnType("int");

                    b.Property<string>("sPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sQueQuan")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sSDT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sTenNhanVien")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sMaNhanVien");

                    b.ToTable("ThuThus");
                });

            modelBuilder.Entity("Database.Model.YeuCauSach", b =>
                {
                    b.Property<int>("sMaYeuCau")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("dNgayMuon")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dNgayTra")
                        .HasColumnType("datetime2");

                    b.Property<int>("sMaDocGia")
                        .HasColumnType("int");

                    b.Property<int>("sMaSach")
                        .HasColumnType("int");

                    b.Property<int>("sTrangThai")
                        .HasColumnType("int");

                    b.HasKey("sMaYeuCau");

                    b.HasIndex("sMaDocGia");

                    b.HasIndex("sMaSach");

                    b.ToTable("YeuCauSachs");
                });

            modelBuilder.Entity("Database.Model.TheMuon", b =>
                {
                    b.HasOne("Database.Model.DocGia", "sDocGia")
                        .WithMany("TheMuons")
                        .HasForeignKey("sMaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Model.ThuThu", "sNhanVien")
                        .WithMany("TheMuons")
                        .HasForeignKey("sMaNhanVien")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Model.Sach", "sSach")
                        .WithMany("TheMuons")
                        .HasForeignKey("sMaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sDocGia");

                    b.Navigation("sNhanVien");

                    b.Navigation("sSach");
                });

            modelBuilder.Entity("Database.Model.YeuCauSach", b =>
                {
                    b.HasOne("Database.Model.DocGia", "sDocGia")
                        .WithMany("YeuCauSachs")
                        .HasForeignKey("sMaDocGia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Database.Model.Sach", "sSach")
                        .WithMany("YeuCauSachs")
                        .HasForeignKey("sMaSach")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sDocGia");

                    b.Navigation("sSach");
                });

            modelBuilder.Entity("Database.Model.DocGia", b =>
                {
                    b.Navigation("TheMuons");

                    b.Navigation("YeuCauSachs");
                });

            modelBuilder.Entity("Database.Model.Sach", b =>
                {
                    b.Navigation("TheMuons");

                    b.Navigation("YeuCauSachs");
                });

            modelBuilder.Entity("Database.Model.ThuThu", b =>
                {
                    b.Navigation("TheMuons");
                });
#pragma warning restore 612, 618
        }
    }
}
